- name: Update and upgrade apt packages on servers
  hosts: servers
  become: yes
  tasks:
    - name: Error Block Handle
      block:
        - name: Update apt cache
          apt:
            update_cache: yes

        - name: Upgrade all packages
          apt:
            upgrade: dist
      rescue:
        - name: "Error Occured"
          ansible.builtin.uri:
            delegate_to: 127.0.0.1
            url: "https://api.telegram.org/bot{{ telegram_token }}/sendMessage?chat_id={{ telegram_chat_id }}&text={{ ansible_play_name }}+Failed"
            method: POST
            headers:
              Content-Type: "application/json"
            body_format: json