- name: Update and upgrade apt packages on servers
  hosts: servers
  become: yes
  tasks:
    - name: Update and upgrade packages
      block:
        - name: Update apt cache
          apt:
            update_cache: yes

        - name: Upgrade all packages
          apt:
            upgrade: dist

      rescue:
        - name: Telegram
          community.general.telegram:
            token: {{ telegram_token }}
            api_args:
              chat_id: {{ telegram_chat_id }}
              text: "Task failed"
            